swagger: "2.0"
info:
  description: "API para serviço de aluguel de motos."
  version: "1.0.0"
  title: "MotoFast"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "motofast-api.herokuapp.com"
basePath: "/"
tags:
- name: "motos"
  description: "Aluguel de motos"
schemes:
- "https"
- "http"
paths:
  /motos:
    get:
      tags:
      - "motos"
      summary: "Lista todas as motos"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Moto"
        "400":
          description: "Invalid status value"
  /motos/{petId}:
    get:
      tags:
      - "motos"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Moto"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
definitions:
  Moto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      marca:
        type: "string"
      modelo:
        type: "string"
      preco:
        type: "number"
      ano:
        type: "string"
      cor:
        type: "string"
      cambio:
        type: "string"